<?php

namespace Database\Seeders;

use App\Models\HorarioTurno;
use App\Models\TipoTurno;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class HorarioTurnoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $registro = HorarioTurno::firstOrCreate([
        //     'tipo_turno_id' => TipoTurno::where('nombre','MAÑANA')->value('id'),
        //     'horaentrada'   => '08:00',
        //     'horasalida'   => '13:00',
        //     'toleranciaantes'   => 5,
        //     'toleranciadespues' => 5,
        //     'inicioentrada'     => '07:55',
        //     'finentrada'        => '08:05',
        //     'iniciosalida'      => '12:55',
        //     'finsalida'         => '12:55',            
        //     'dialunes'          => 1,
        //     'diamartes'         => 1,
        //     'diamiercoles'      => 1,
        //     'diajueves'         => 1,
        //     'diaviernes'        => 1,
        //     'diasabado'         => 1,
        //     'diadomingo'        => 0,
        //     'totalhoras'        => '05:00:00',
        // ]);
    $registros = [



        [
            'tipo_turno_id' => TipoTurno::where('nombre','MAÑANA')->value('id'),
            'horaentrada'   => '08:00',
            'horasalida'   => '13:00',
            'toleranciaantes'   => 5,
            'toleranciadespues' => 5,
            'inicioentrada'     => '07:55',
            'finentrada'        => '08:05',
            'iniciosalida'      => '12:55',
            'finsalida'         => '12:55',            
            'dialunes'          => 1,
            'diamartes'         => 1,
            'diamiercoles'      => 1,
            'diajueves'         => 1,
            'diaviernes'        => 1,
            'diasabado'         => 1,
            'diadomingo'        => 0,
            'totalhoras'        => '05:00:00',
        ],
        [
            'tipo_turno_id' => TipoTurno::where('nombre','MAÑANA Y TARDE')->value('id'),
            'horaentrada' => '08:00:00',
            'horasalida' => '13:00:00',
            'toleranciaantes' => 5,
            'toleranciadespues' => 5,
            'inicioentrada' => '07:55:00',
            'finentrada' => '08:05:00',
            'iniciosalida' => '12:55:00',
            'finsalida' => '12:55:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 1,
            'diadomingo' => 0,
            'totalhoras' => '00:00:30',
        ],
        [
            'tipo_turno_id' => TipoTurno::where('nombre','TARDE')->value('id'),
            'horaentrada' => '08:00:00',
            'horasalida' => '13:00:00',
            'toleranciaantes' => 5,
            'toleranciadespues' => 0,
            'inicioentrada' => '07:30:00',
            'finentrada' => '08:30:00',
            'iniciosalida' => '13:00:00',
            'finsalida' => '15:30:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '00:00:40',
        ],
        [
            'tipo_turno_id' => TipoTurno::where('nombre','TARDE')->value('id'),
            'horaentrada' => '14:30:00',
            'horasalida' => '17:30:00',
            'toleranciaantes' => 10,
            'toleranciadespues' => 0,
            'inicioentrada' => '14:00:00',
            'finentrada' => '14:40:00',
            'iniciosalida' => '17:30:00',
            'finsalida' => '17:30:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '15:00:00',
        ],
        [
            'tipo_turno_id' => 2,
            'horaentrada' => '08:00:00',
            'horasalida' => '13:00:00',
            'toleranciaantes' => 5,
            'toleranciadespues' => 5,
            'inicioentrada' => '07:55:00',
            'finentrada' => '08:05:00',
            'iniciosalida' => '12:55:00',
            'finsalida' => '12:55:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '00:00:25',
        ],
        [
            'tipo_turno_id' => 9,
            'horaentrada' => '08:00:00',
            'horasalida' => '13:00:00',
            'toleranciaantes' => 0,
            'toleranciadespues' => 5,
            'inicioentrada' => '07:30:00',
            'finentrada' => '13:30:00',
            'iniciosalida' => '13:00:00',
            'finsalida' => '13:45:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '05:00:00',
        ],
        [
            'tipo_turno_id' => 10,
            'horaentrada' => '14:30:00',
            'horasalida' => '17:30:00',
            'toleranciaantes' => 0,
            'toleranciadespues' => 10,
            'inicioentrada' => '14:30:00',
            'finentrada' => '14:40:00',
            'iniciosalida' => '17:30:00',
            'finsalida' => '18:00:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '03:00:00',
        ],
        [
            'tipo_turno_id' => 10,
            'horaentrada' => '05:00:00',
            'horasalida' => '13:00:00',
            'toleranciaantes' => 60,
            'toleranciadespues' => 5,
            'inicioentrada' => '04:00:00',
            'finentrada' => '05:30:00',
            'iniciosalida' => '13:00:00',
            'finsalida' => '14:00:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 0,
            'diadomingo' => 0,
            'totalhoras' => '08:00:00',
        ],
        [
            'tipo_turno_id' => 11,
            'horaentrada' => '07:30:00',
            'horasalida' => '07:30:00',
            'toleranciaantes' => 0,
            'toleranciadespues' => 0,
            'inicioentrada' => '07:00:00',
            'finentrada' => '08:00:00',
            'iniciosalida' => '07:30:00',
            'finsalida' => '07:30:00',
            'dialunes' => 1,
            'diamartes' => 1,
            'diamiercoles' => 1,
            'diajueves' => 1,
            'diaviernes' => 1,
            'diasabado' => 1,
            'diadomingo' => 1,
            'totalhoras' => '00:00:00',
        ],
    ];
    foreach($registros as $fila){
        HorarioTurno::firstOrCreate($fila);
    }



    }
}
